package com.example.bean;
// Generated 2017-6-25 17:05:32 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Conditions generated by hbm2java
 */
public class Conditions implements java.io.Serializable {

	private String conditionId;
	private String description;
	private Set goodsStatuses = new HashSet(0);

	public Conditions() {
	}

	public Conditions(String conditionId, String description) {
		this.conditionId = conditionId;
		this.description = description;
	}

	public Conditions(String conditionId, String description, Set goodsStatuses) {
		this.conditionId = conditionId;
		this.description = description;
		this.goodsStatuses = goodsStatuses;
	}

	public String getConditionId() {
		return this.conditionId;
	}

	public void setConditionId(String conditionId) {
		this.conditionId = conditionId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getGoodsStatuses() {
		return this.goodsStatuses;
	}

	public void setGoodsStatuses(Set goodsStatuses) {
		this.goodsStatuses = goodsStatuses;
	}

}
