package bean;
// Generated 2017-6-25 17:05:32 by Hibernate Tools 3.5.0.Final

/**
 * GoodsStatus generated by hbm2java
 */
public class GoodsStatus implements java.io.Serializable {

	private GoodsStatusId id;
	private Goods goods;
	private Conditions conditions;

	public GoodsStatus() {
	}

	public GoodsStatus(GoodsStatusId id, Goods goods, Conditions conditions) {
		this.id = id;
		this.goods = goods;
		this.conditions = conditions;
	}

	public GoodsStatusId getId() {
		return this.id;
	}

	public void setId(GoodsStatusId id) {
		this.id = id;
	}

	public Goods getGoods() {
		return this.goods;
	}

	public void setGoods(Goods goods) {
		this.goods = goods;
	}

	public Conditions getConditions() {
		return this.conditions;
	}

	public void setConditions(Conditions conditions) {
		this.conditions = conditions;
	}

}
