package bean;
// Generated 2017-6-25 17:05:32 by Hibernate Tools 3.5.0.Final

/**
 * GoodsStatusId generated by hbm2java
 */
public class GoodsStatusId implements java.io.Serializable {

	private String goodsId;
	private String conditionId;

	public GoodsStatusId() {
	}

	public GoodsStatusId(String goodsId, String conditionId) {
		this.goodsId = goodsId;
		this.conditionId = conditionId;
	}

	public String getGoodsId() {
		return this.goodsId;
	}

	public void setGoodsId(String goodsId) {
		this.goodsId = goodsId;
	}

	public String getConditionId() {
		return this.conditionId;
	}

	public void setConditionId(String conditionId) {
		this.conditionId = conditionId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GoodsStatusId))
			return false;
		GoodsStatusId castOther = (GoodsStatusId) other;

		return ((this.getGoodsId() == castOther.getGoodsId()) || (this.getGoodsId() != null
				&& castOther.getGoodsId() != null && this.getGoodsId().equals(castOther.getGoodsId())))
				&& ((this.getConditionId() == castOther.getConditionId())
						|| (this.getConditionId() != null && castOther.getConditionId() != null
								&& this.getConditionId().equals(castOther.getConditionId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getGoodsId() == null ? 0 : this.getGoodsId().hashCode());
		result = 37 * result + (getConditionId() == null ? 0 : this.getConditionId().hashCode());
		return result;
	}

}
