package bean;
// Generated 2017-6-25 17:05:32 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * ProvinceCenter generated by hbm2java
 */
public class ProvinceCenter implements java.io.Serializable {

	private Integer centerId;
	private String province;
	private String pwd;
	private Set goodsesForSendProvinceCenter = new HashSet(0);
	private Set goodsesForReceiveProvinceCenter = new HashSet(0);
	private Set transportationManagements = new HashSet(0);

	public ProvinceCenter() {
	}

	public ProvinceCenter(String province, String pwd) {
		this.province = province;
		this.pwd = pwd;
	}

	public ProvinceCenter(String province, String pwd, Set goodsesForSendProvinceCenter,
			Set goodsesForReceiveProvinceCenter, Set transportationManagements) {
		this.province = province;
		this.pwd = pwd;
		this.goodsesForSendProvinceCenter = goodsesForSendProvinceCenter;
		this.goodsesForReceiveProvinceCenter = goodsesForReceiveProvinceCenter;
		this.transportationManagements = transportationManagements;
	}

	public Integer getCenterId() {
		return this.centerId;
	}

	public void setCenterId(Integer centerId) {
		this.centerId = centerId;
	}

	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public Set getGoodsesForSendProvinceCenter() {
		return this.goodsesForSendProvinceCenter;
	}

	public void setGoodsesForSendProvinceCenter(Set goodsesForSendProvinceCenter) {
		this.goodsesForSendProvinceCenter = goodsesForSendProvinceCenter;
	}

	public Set getGoodsesForReceiveProvinceCenter() {
		return this.goodsesForReceiveProvinceCenter;
	}

	public void setGoodsesForReceiveProvinceCenter(Set goodsesForReceiveProvinceCenter) {
		this.goodsesForReceiveProvinceCenter = goodsesForReceiveProvinceCenter;
	}

	public Set getTransportationManagements() {
		return this.transportationManagements;
	}

	public void setTransportationManagements(Set transportationManagements) {
		this.transportationManagements = transportationManagements;
	}

}
