package bean;
// Generated 2017-6-25 17:05:32 by Hibernate Tools 3.5.0.Final

/**
 * TransportationManagement generated by hbm2java
 */
public class TransportationManagement implements java.io.Serializable {

	private TransportationManagementId id;
	private Transportation transportation;
	private ProvinceCenter provinceCenter;

	public TransportationManagement() {
	}

	public TransportationManagement(TransportationManagementId id, Transportation transportation,
			ProvinceCenter provinceCenter) {
		this.id = id;
		this.transportation = transportation;
		this.provinceCenter = provinceCenter;
	}

	public TransportationManagementId getId() {
		return this.id;
	}

	public void setId(TransportationManagementId id) {
		this.id = id;
	}

	public Transportation getTransportation() {
		return this.transportation;
	}

	public void setTransportation(Transportation transportation) {
		this.transportation = transportation;
	}

	public ProvinceCenter getProvinceCenter() {
		return this.provinceCenter;
	}

	public void setProvinceCenter(ProvinceCenter provinceCenter) {
		this.provinceCenter = provinceCenter;
	}

}
