package bean;
// Generated 2017-6-25 17:05:32 by Hibernate Tools 3.5.0.Final

/**
 * TransportationManagementId generated by hbm2java
 */
public class TransportationManagementId implements java.io.Serializable {

	private int centerId;
	private String transportationId;

	public TransportationManagementId() {
	}

	public TransportationManagementId(int centerId, String transportationId) {
		this.centerId = centerId;
		this.transportationId = transportationId;
	}

	public int getCenterId() {
		return this.centerId;
	}

	public void setCenterId(int centerId) {
		this.centerId = centerId;
	}

	public String getTransportationId() {
		return this.transportationId;
	}

	public void setTransportationId(String transportationId) {
		this.transportationId = transportationId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TransportationManagementId))
			return false;
		TransportationManagementId castOther = (TransportationManagementId) other;

		return (this.getCenterId() == castOther.getCenterId())
				&& ((this.getTransportationId() == castOther.getTransportationId())
						|| (this.getTransportationId() != null && castOther.getTransportationId() != null
								&& this.getTransportationId().equals(castOther.getTransportationId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCenterId();
		result = 37 * result + (getTransportationId() == null ? 0 : this.getTransportationId().hashCode());
		return result;
	}

}
